# Generated by Django 3.2.18 on 2023-04-26 01:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_auto_20230228_1251'),
        ('employee_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Worker ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employee_information.employees', verbose_name='Employee ID')),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.ward', verbose_name='Ward ID')),
            ],
            options={
                'verbose_name_plural': 'Worker',
            },
        ),
    ]
