# Generated by Django 3.2.18 on 2023-04-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_auto_20230228_1251'),
        ('employee_information', '0002_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='ward_id',
        ),
        migrations.AddField(
            model_name='worker',
            name='ward_id',
            field=models.ManyToManyField(to='garden.Ward', verbose_name='Ward ID'),
        ),
    ]
