# Generated by Django 3.2.18 on 2023-02-16 04:20

import complaint_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=complaint_management.models.upload_to),
        ),
    ]
