# Generated by Django 3.2.18 on 2023-02-28 06:43

from django.db import migrations, models
import django.db.models.deletion
import garden.models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_alter_garden_garden_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=garden.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.garden')),
            ],
            options={
                'verbose_name_plural': 'Ratings',
            },
        ),
    ]
