# Generated by Django 3.2.18 on 2023-02-28 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garden', '0003_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ratings',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
    ]
